### ISSUE TITLE
Contributions and revisions page out of date

### ISSUE THREAD

**Issue by abroniewski** [MobilityDB/MobilityDB-workshop#13]
- add Ismail and Adam
- add revision information to cover page

**Comment by Lorenc1o** [comment]
I have updated the contributions guidelines according to what I have experienced. If someone could give it a check it would be nice. Then we can close this issue.

**Comment by abroniewski** [comment]
@Lorenc1o  Can you link to the guidelines that were updated? I can't seem to see the changes.

**Comment by Lorenc1o** [comment]
Sure, it's the develop branch: https://github.com/MobilityDB/MobilityDB-workshop/blob/develop/CONTRIBUTING.md

**Comment by abroniewski** [comment]
Awesome! That's much cleaner and provides the high level that was missing. 

We're you able to complete updates to the DocBook with a single tool? I originally included the detailed instructions because of some encoding issues with the DocBook version being used...

**Comment by Lorenc1o** [comment]
Before, there was some mention about exporting a Notion (that I was not able to find).

I just updated the raw XML files. If you do it like this, there should be no problem with the compiling! In any case, writing directly in XML is not as bad as it seems... If anyways you want to provide a means for doing this in markdown, we should either:
- Find an easy way to achieve this. Exporting twice from XML to MD and back does not seem like the best way. Maybe there is a better tool for that.
- Change everything to markdown. This would probably be easier in the longer run, but the whole repo should be restructured and we should find a way to produce the pdf, epub and html from md (this part should be easy).

What do you think?

**Comment by abroniewski** [comment]
The content for the chapter Ismail and I developed was new. We did the majority of our work in Notion, and I wanted to provide an easy way for others to contribute. We didn't start in XML, and so it was much more convenient to transfer from Notion to XML.

If you're experience in XML editing was smooth, then I think we should leave it as is without any mention of markdown or Notion.

Thanks for making all of these edits and updating the documentation! It's really refreshing to see things cleaned up a bit.

**Comment by Lorenc1o** [comment]
Perfect, then! 

I can close the issue if you are OK with that :smile:

**Comment by abroniewski** [comment]
Does it make sense to add something about having contributors add their names as Authors in the cover page as well?

(FYI - I just did that now for Ismail and I for the Flight Dashboard chapter).

**Comment by Lorenc1o** [comment]
Done!
