### ISSUE TITLE
Docker information in the README.md file

### ISSUE THREAD

**Issue by estebanzimanyi** [MobilityDB/MobilityDB-workshop#14]
The README.md file in the repository mentions a docker container solution, and the information there is outdated, in particular PostGIS 2.5 is no longer supported, since PostGIS will EOL this version in the forthcoming months.
Having a docker solution for the workshop will very useful for future users exploring MobilityDB to determine whether it is a solution for their application.

**Comment by abroniewski** [comment]
@herozero777 reviewing the docker image would be a good update to complete. This could include:
- Updating all docker installations to most up to date dependencies
- Running the workshops through the docker install for QA
- Reviewing and updating the documentation for installation and running

lets discuss when we can move this forward.
