### ISSUE TITLE
Chapter 2 : missing column service_id  in trips_mdb table.

### ISSUE THREAD

**Issue by sswirydo** [MobilityDB/MobilityDB-workshop#5]
**Problem:**
Missing column in the last query of Chapter 2: Managing GTFS Data.

**Details:**
Executing:
```sql
INSERT INTO trips_mdb(trip_id, service_id, route_id, date, trip)
SELECT trip_id, route_id, t.service_id, d.date,
  shift(trip, make_interval(days => d.date - t.date))
FROM trips_mdb t JOIN service_dates d ON t.service_id = d.service_id AND t.date <> d.date;
```
results in the following error:
```sql
ERROR:  column "service_id" of relation "trips_mdb" does not exist
```

Reminder: trips_mdb is defined as follows:
```sql
  CREATE TABLE trips_mdb (
    trip_id text NOT NULL,
    route_id text NOT NULL,
    date date NOT NULL,
    trip tgeompoint,
    PRIMARY KEY (trip_id, date)
  );
```

Which means that both the join on _service_id_, and the insertion of _service_id_ into _trips_mdb_ does not make sense at the moment.

**Comment by jemappellesami** [comment]
Hi,
I had the same problem and solved it by adding a "service_id" column at the creation of trips_mdb table, taking it from the trips_input table.

The correction goes as follows : 
`DROP TABLE IF EXISTS trips_mdb;
CREATE TABLE trips_mdb (
  trip_id text NOT NULL,
  route_id text NOT NULL,
-- notice here the change
  service_id text NOT NULL,
  date date NOT NULL,
  trip tgeompoint,
  PRIMARY KEY (trip_id, date)
);

INSERT INTO trips_mdb(trip_id, route_id, service_id, date, trip)
-- here again
SELECT trip_id, route_id, service_id, date,
  tgeompoint_seq(array_agg(tgeompoint_inst(point_geom, t) ORDER BY T))
FROM trips_input
-- and here
GROUP BY trip_id, route_id, service_id, date;`

**Comment by Lorenc1o** [comment]
This has been corrected in the updated version of the workshop for MobilityDB 1.1.
